# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Radicale installation tasks
  when: radicale_enabled | bool
  tags:
    - setup-all
    - setup-radicale
    - install-all
    - install-radicale
  block:
    - name: Validate Radicale configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Radicale
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Radicale uninstallation tasks
  when: not radicale_enabled | bool
  tags:
    - setup-all
    - setup-radicale
  block:
    - name: Uninstall Radicale
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
