# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Radicale installation tasks
  block:
    - name: Validate Radicale configuration
      when: radicale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Radicale
      when: radicale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-radicale
    - install-all
    - install-radicale

- name: Perform Radicale uninstallation tasks
  block:
    - name: Uninstall Radicale
      when: not radicale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-radicale
