# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Radicale systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ radicale_identifier }}.service"
  register: radicale_service_stat

- name: Uninstall Radicale systemd services and files
  when: radicale_service_stat.stat.exists | bool
  block:
    - name: Ensure Radicale systemd service is stopped
      ansible.builtin.service:
        name: "{{ radicale_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Radicale systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ radicale_identifier }}.service"
        state: absent

    - name: Ensure Radicale support files do not exist
      ansible.builtin.file:
        path: "{{ radicale_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Radicale image source files path does not exist
      ansible.builtin.file:
        path: "{{ radicale_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure Radicale local config path does not exist
      # Removing the path should be fine because it is used for mounting the configuration file generated on the template
      ansible.builtin.file:
        path: "{{ radicale_config_path }}"
        state: absent

    - name: Ensure Radicale local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ radicale_data_path }}"
      register: radicale_data_path_deletion_result
      changed_when: radicale_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Radicale base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ radicale_base_path }}"
      register: radicale_base_path_deletion_result
      changed_when: radicale_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Radicale container network does not exist
      when: radicale_container_network_deletion_enabled
      block:
        - name: Ensure Radicale container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ radicale_container_network }}"
            state: absent
          register: radicale_network_deletion_result

        - name: Ensure Radicale container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ radicale_container_network }}
          register: radicale_network_deletion_result
          changed_when: radicale_container_network in radicale_network_deletion_result.stdout

- name: Check existence of Radicale local data path
  ansible.builtin.stat:
    path: "{{ radicale_data_path }}"
  register: radicale_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Radicale local data path
  when: radicale_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Radicale instance has been removed, local data remains in `" + radicale_data_path + "`. Feel free to delete it."
        ]
      }}
