# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# We do this locally, so that we won't need passlib to be installed on the server.
- name: Generate Basic Auth file locally
  community.general.htpasswd:
    path: "{{ radicale_credentials_basicauth_file_tmp }}"
    name: "{{ credential_entry.username }}"
    password: "{{ credential_entry.password }}"
    mode: "0640"
  become: false
  delegate_to: 127.0.0.1

- name: Load Basic Auth file contents
  ansible.builtin.slurp:
    src: "{{ radicale_credentials_basicauth_file_tmp }}"
  become: false
  delegate_to: 127.0.0.1
  register: radicale_basicauth_file_contents_raw

- name: Load Basic Auth file contents
  ansible.builtin.set_fact:
    radicale_basicauth_file_contents: "{{ radicale_basicauth_file_contents_raw['content'] | b64decode | trim }}"

- name: Inject credentials into radicale_htpasswds
  ansible.builtin.set_fact:
    radicale_htpasswds: "{{ radicale_htpasswds + [radicale_basicauth_file_contents] }}"

- name: Ensure local temporary Basic Auth file is removed
  ansible.builtin.file:
    path: "{{ radicale_credentials_basicauth_file_tmp }}"
    state: absent
  become: false
  delegate_to: 127.0.0.1
